import os
import sys

# Ensure that the script always runs with the repository root
# added to PYTHONPATH, regardless of where it is executed from.
os.chdir(os.path.dirname(os.path.abspath(__file__)))
repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)

import argparse
import ast
import json
import logging
import random

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim

from routerl import TrafficEnvironment
from tqdm import tqdm

from baseline_models import BaseLearningModel
from utils import *
import xml.etree.ElementTree as ET

import torch.nn.functional as F

import shutil

import networkx as nx
import matplotlib.pyplot as plt

from torch_geometric.data import Data
from torch_geometric.utils import to_networkx, from_scipy_sparse_matrix
from torch_geometric.nn import GCNConv

from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

from visualize_flow import TrafficAnimator

import scipy.sparse as sp

os.environ['PROJ_LIB'] = '/opt/homebrew/share/proj'

testing_needed = False
snapshot_analysis = True

class Network(nn.Module):
    def __init__(self, in_size, out_size, num_hidden, widths):
        super(Network, self).__init__()
        assert len(widths) == (num_hidden + 1), "DQN widths and number of layers mismatch!"
        
        self.input_layer = nn.Linear(in_size, widths[0])
        self.hidden_layers = nn.ModuleList([nn.Linear(widths[x], widths[x+1]) for x in range(num_hidden)])
        self.out_layer = nn.Linear(widths[-1], out_size)

    def forward(self, x):
        x = torch.relu(self.input_layer(x))
        for hidden_layer in self.hidden_layers:
            x = torch.relu(hidden_layer(x))
        x = self.out_layer(x)
        return x

class PPO(BaseLearningModel):
    """
    Proximal Policy Optimization (PPO) agent whose policy parameters
    are generated by a shared HyperNetwork.
    """
    def __init__(self,
            state_size, 
            action_space_size, 
            agent_id,
            device="cpu", 
            batch_size=16, 
            lr=0.003, 
            num_epochs=4, 
            hidden_sizes=[32, 64, 32], 
            clip_eps=0.2, 
            normalize_advantage=True, 
            entropy_coef=0.3, 
            total_training_eps=10000
        ):
        """
        Initialize PPO agent with shared HyperNetwork.
        """
        super().__init__()
        self.device = device
        self.state_size = state_size
        self.action_space_size = action_space_size
        self.agent_id = agent_id
        self.batch_size = batch_size
        self.num_epochs = num_epochs
        self.clip_eps = clip_eps
        self.normalize_advantage = normalize_advantage
        self.entropy_coef = entropy_coef
        self.initial_entropy_coef = entropy_coef
        self.hidden_sizes = hidden_sizes
        self.total_training_eps = total_training_eps
        self.num_hidden = len(hidden_sizes)
        self.softmax = nn.Softmax(dim=-1)
        self.policy_net = Network(state_size, action_space_size, num_hidden, hidden_sizes).to(self.device)
        self.optimizer = optim.Adam(self.policy_net.parameters(), lr=lr)
        
        # Linear learning-rate decay
        self.scheduler = optim.lr_scheduler.LinearLR(self.optimizer, start_factor=1.0, end_factor=0.01, total_iters=total_training_eps)
        
        self.memory = []
        self.loss = []
        self.deterministic = False

    def update_params(self, episode):
        """
        Update learning rate and entropy coefficient schedule.
        """
        self.scheduler.step()
        self.entropy_coef = self.initial_entropy_coef * max(
            0.01,
            (1 -episode / self.total_training_eps)
        )

    def _get_weights(self):
        """
        Generate policy network weights and biases for this agent.
        """
        agent_embed = self.agent_embeddings(self.agent_id)
        params = self.hypernet(agent_embed)
        
        weights, biases = [], []
        idx = 0
        layer_sizes = [self.state_size] + self.hidden_sizes + [self.action_space_size]
        
        for i in range(len(layer_sizes) - 1):
            w_size = layer_sizes[i] * layer_sizes[i+1]
            b_size = layer_sizes[i+1]
            
            weights.append(params[idx:idx + w_size].view(layer_sizes[i], layer_sizes[i+1]))
            idx += w_size
            
            biases.append(params[idx:idx + b_size])
            idx += b_size

        return weights, biases


    def act(self, state):
        """
        Sample or select an action given the current state.
        """
        state_tensor = torch.FloatTensor(state).unsqueeze(0).to(self.device)
        with torch.no_grad():
            logits = self.policy_net(state_tensor)
            probs = self.softmax(logits)
        dist = torch.distributions.Categorical(probs)
        action = torch.argmax(probs) if self.deterministic else dist.sample()

        self.last_state = state_tensor.detach().cpu().numpy()
        self.last_action = action.item()
        self.last_log_prob = dist.log_prob(action).item()

        return action.item()
    
    def push(self, reward):
        """
        Store transition reward in replay buffer.
        """
        self.memory.append((
            self.last_state,
            self.last_action,
            self.last_log_prob,
            reward
        ))

    def learn(self):
        """
        Perform PPO update using stored transitions.
        """
        if len(self.memory) < self.batch_size:
            return

        step_losses = []

        for _ in range(self.num_epochs):
            batch = random.sample(self.memory, self.batch_size)
            states, actions, old_log_probs, rewards = zip(*batch)

            # Remove extra singleton dimension from states
            states = torch.FloatTensor(np.array(states)).to(self.device).squeeze(1)
            actions = torch.LongTensor(actions).to(self.device)
            old_log_probs = torch.FloatTensor(old_log_probs).to(self.device)
            rewards = torch.FloatTensor(rewards).to(self.device)

            weights, biases = self._get_weights()
            logits = functional_mlp(states, weights, biases)
            dist = torch.distributions.Categorical(logits=logits)
            
            new_log_probs = dist.log_prob(actions)
            ratio = torch.exp(new_log_probs - old_log_probs)

            # Advantage normalization
            adv = (rewards - rewards.mean()) / (rewards.std() + 1e-8) if self.normalize_advantage else rewards

            surr1 = ratio * adv
            surr2 = torch.clamp(ratio, 1 - self.clip_eps, 1 + self.clip_eps) * adv

            # PPO objective with entropy regularization
            loss = -torch.min(surr1, surr2).mean() - self.entropy_coef * dist.entropy().mean()

            self.optimizer.zero_grad()
            loss.backward()
            # Gradient clipping for shared parameters
            torch.nn.utils.clip_grad_norm_(list(self.hypernet.parameters()) + list(self.agent_embeddings.parameters()), 1)
            self.optimizer.step()
            step_losses.append(loss.item())

        self.loss.append(np.mean(step_losses))
        self.memory.clear()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--id', type=str, required=True)
    parser.add_argument('--env-conf', type=str, default="config1")
    parser.add_argument('--task-conf', type=str, required=True)
    parser.add_argument('--alg-conf', type=str, required=True)
    parser.add_argument('--net', type=str, required=True)
    parser.add_argument('--env-seed', type=int, default=42)
    parser.add_argument('--torch-seed', type=int, default=42)
    args = parser.parse_args()

    ALGORITHM = "rl_alg"
    exp_id = args.id
    env_config = args.env_conf
    task_config = args.task_conf
    alg_config = args.alg_conf
    network = args.net
    env_seed = args.env_seed
    torch_seed = args.torch_seed

    print("### STARTING EXPERIMENT ###")
    print(f"Algorithm: {ALGORITHM.upper()}")
    print(f"Experiment ID: {exp_id}")
    print(f"Network: {network}")
    print(f"Environment seed: {env_seed}")
    print(f"Torch seed: {torch_seed}")
    print(f"Algorithm config: {alg_config}")
    print(f"Environment config: {env_config}")
    print(f"Task config: {task_config}")
    
    os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
    logging.getLogger("matplotlib").setLevel(logging.ERROR)

    custom_network_folder = f"networks/{network}"
    records_folder = f"results/{exp_id}"
    snapshots_dir = os.path.join(records_folder, "snapshots")
    plots_folder = f"{records_folder}/plots"

    os.makedirs(records_folder, exist_ok=True)
    os.makedirs(snapshots_dir, exist_ok=True)
    os.makedirs(plots_folder, exist_ok=True)
    
    torch.manual_seed(torch_seed)
    torch.cuda.manual_seed_all(torch_seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    random.seed(env_seed)
    np.random.seed(env_seed)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("Device is:", device)
    params = {}
    params.update(json.load(open(f"config/algo_config/{ALGORITHM}/{alg_config}.json")))
    params.update(json.load(open(f"config/env_config/{env_config}.json")))
    params.update(json.load(open(f"config/task_config/{task_config}.json")))
    del params["desc"]

    for k, v in params.items():
        globals()[k] = v

    phases = [1, human_learning_episodes, int(training_eps) + human_learning_episodes]
    phase_names = ["Human stabilization", "Mutation and AV learning", "Testing phase"]

    with open(os.path.join(custom_network_folder, f"od_{network}.txt")) as f:
        od_data = ast.literal_eval(f.read())

    origins = od_data["origins"]
    destinations = od_data["destinations"]

    agents_csv = os.path.join(custom_network_folder, "agents.csv")
    agents_df = pd.read_csv(agents_csv)
    agents_df.to_csv(os.path.join(records_folder, "agents.csv"), index=False)

    num_agents = len(agents_df)
    max_start_time = agents_df["start_time"].max()
    num_machines = int(num_agents * ratio_machines)
    total_episodes = human_learning_episodes + training_eps + test_eps

    dump_config = params.copy()
    dump_config.update({
        "network": network,
        "env_seed": env_seed,
        "torch_seed": torch_seed,
        "algorithm": ALGORITHM,
        "num_agents": num_agents,
        "num_machines": num_machines,
        "script": os.path.abspath(__file__)
    })

    with open(os.path.join(records_folder, "exp_config.json"), "w") as f:
        json.dump(dump_config, f, indent=4)

    env = TrafficEnvironment(
        seed=env_seed,
        create_agents=False,
        create_paths=True,
        save_detectors_info=False,
        agent_parameters={
            "new_machines_after_mutation": num_machines,
            "human_parameters": {"model": human_model},
            "machine_parameters": {
                "behavior": av_behavior,
                "observation_type": "previous_agents_plus_start_time"
            }
        },
        environment_parameters={"save_every": save_every},
        simulator_parameters={
            "network_name": network,
            "custom_network_folder": custom_network_folder,
            "sumo_type": "sumo",
            "simulation_timesteps": max_start_time
        },
        plotter_parameters={
            "phases": phases,
            "phase_names": phase_names,
            "smooth_by": smooth_by,
            "plot_choices": plot_choices,
            "records_folder": records_folder,
            "plots_folder": plots_folder
        },
        path_generation_parameters={
            "origins": origins,
            "destinations": destinations,
            "number_of_paths": number_of_paths,
            "beta": path_gen_beta,
            "num_samples": num_samples,
            "visualize_paths": False,
        }
    )

    ### SIMULATION SETUP AND TRAINING LOOP ###

    env.start()
    env.reset()
    
    pbar = tqdm(total=total_episodes, desc="Human learning")
    for _ in range(human_learning_episodes):
        env.step()
        pbar.update()
    
    env.mutation(disable_human_learning=not should_humans_adapt,
        mutation_start_percentile=-1)
    
    obs_size = env.observation_space(env.possible_agents[0]).shape[0]
    action_size = env.machine_agents[0].action_space_size

    machine_ids = [int(a.id) for a in env.machine_agents]
    machine_features_df = agents_df[agents_df['id'].isin(machine_ids)].reset_index(drop=True)

    ### AGENT MODEL INITIALIZATION ###

    for idx, agent in enumerate(env.machine_agents):
        agent.model = PPO(
            state_size=obs_size,
            action_space_size=action_size,
            agent_id=idx,
            device=device,
            batch_size=batch_size,
            lr=lr,
            num_epochs=num_epochs,
            hidden_sizes=widths,
            clip_eps=clip_eps,
            normalize_advantage=normalize_advantage,
            entropy_coef=entropy_coef,
            total_training_eps=training_eps
        )
    agent_lookup = {str(agent.id): agent for agent in env.machine_agents}

    ### AV LEARNING PHASE ###
    
    no_snaps = 4000
    
    pbar.set_description("AV learning")
    os.makedirs(plots_folder, exist_ok=True)
    for episode in range(training_eps):

        env.reset()
        env.machine_agents[0].model.update_params(episode) 
        snapshot_interval = 1
        snapshots_taken = 0
        episode_snapshots = [] 

        for agent_id in env.agent_iter():
            obs, reward, term, trunc, _ = env.last()
            
            current_sim_step = env.unwrapped.simulator.timestep
           
            if snapshots_taken < no_snaps:
                snap_path = env.unwrapped.simulator.save_snapshot_two(episode, snapshots_taken)
                snapshots_taken += 1

            if term or trunc:
                if agent_id in agent_lookup:
                    agent_lookup[agent_id].model.push(reward)
                    if episode % update_every == 0:
                        agent_lookup[agent_id].model.learn()
                action = None
            else:
                action = agent_lookup[agent_id].model.act(obs)
            env.step(action)

        pbar.update()

    pbar.set_description("Testing")
    for _ in range(test_eps):
        env.reset()
        for agent_id in env.agent_iter():
            obs, _, term, trunc, _ = env.last()
            action = None if (term or trunc) else agent_lookup[agent_id].model.act(obs)
            env.step(action)
        pbar.update()

    pbar.close()
    env.stop_simulation()

    shutil.copytree(
        os.path.join(records_folder, "SUMO_output"),
        snapshots_dir,
        dirs_exist_ok=True
    )