import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import random
from .networks import Network
from baseline_models import BaseLearningModel


class PPO(BaseLearningModel):
    """
    Proximal Policy Optimization (PPO) agent whose policy parameters
    are generated by a shared HyperNetwork.
    """

    def __init__(
        self,
        state_size,
        action_space_size,
        agent_id,
        device="cpu",
        batch_size=16,
        lr=0.003,
        num_epochs=4,
        hidden_sizes=[32, 64, 32],
        clip_eps=0.2,
        normalize_advantage=True,
        entropy_coef=0.3,
        total_training_eps=10000,
    ):
        """
        Initialize PPO agent with shared HyperNetwork.
        """
        super().__init__()
        self.device = device
        self.state_size = state_size
        self.action_space_size = action_space_size
        self.agent_id = agent_id
        self.batch_size = batch_size
        self.num_epochs = num_epochs
        self.clip_eps = clip_eps
        self.normalize_advantage = normalize_advantage
        self.entropy_coef = entropy_coef
        self.initial_entropy_coef = entropy_coef
        self.hidden_sizes = hidden_sizes
        self.total_training_eps = total_training_eps
        self.num_hidden = len(hidden_sizes) - 1
        self.softmax = nn.Softmax(dim=-1)
        self.policy_net = Network(
            state_size, action_space_size, self.num_hidden, hidden_sizes
        ).to(self.device)

        self.optimizer = optim.Adam(self.policy_net.parameters(), lr=lr)

        # Linear learning-rate decay
        self.scheduler = optim.lr_scheduler.LinearLR(
            self.optimizer,
            start_factor=1.0,
            end_factor=0.01,
            total_iters=total_training_eps,
        )

        self.memory = []
        self.loss = []
        self.deterministic = False

    def update_params(self, episode):
        """
        Update learning rate and entropy coefficient schedule.
        """
        self.scheduler.step()
        self.entropy_coef = self.initial_entropy_coef * max(
            0.01, (1 - episode / self.total_training_eps)
        )

    def _get_weights(self):
        """
        Generate policy network weights and biases for this agent.
        """
        agent_embed = self.agent_embeddings(self.agent_id)
        params = self.hypernet(agent_embed)

        weights, biases = [], []
        idx = 0
        layer_sizes = [self.state_size] + self.hidden_sizes + [self.action_space_size]

        for i in range(len(layer_sizes) - 1):
            w_size = layer_sizes[i] * layer_sizes[i + 1]
            b_size = layer_sizes[i + 1]

            weights.append(
                params[idx : idx + w_size].view(layer_sizes[i], layer_sizes[i + 1])
            )
            idx += w_size

            biases.append(params[idx : idx + b_size])
            idx += b_size

        return weights, biases

    def act(self, state):
        """
        Sample or select an action given the current state.
        """
        state_tensor = torch.FloatTensor(state).unsqueeze(0).to(self.device)
        with torch.no_grad():
            logits = self.policy_net(state_tensor)
            probs = self.softmax(logits)
        dist = torch.distributions.Categorical(probs)
        action = torch.argmax(probs) if self.deterministic else dist.sample()

        self.last_state = state_tensor.detach().cpu().numpy()
        self.last_action = action.item()
        self.last_log_prob = dist.log_prob(action).item()

        return action.item()

    def push(self, reward):
        """
        Store transition reward in replay buffer.
        """
        self.memory.append(
            (self.last_state, self.last_action, self.last_log_prob, reward)
        )

    def learn(self):
        """
        Perform PPO update using stored transitions.
        """
        if len(self.memory) < self.batch_size:
            return

        step_losses = []

        for _ in range(self.num_epochs):
            batch = random.sample(self.memory, self.batch_size)
            states, actions, old_log_probs, rewards = zip(*batch)

            # Remove extra singleton dimension from states
            states = torch.FloatTensor(np.array(states)).to(self.device).squeeze(1)
            actions = torch.LongTensor(actions).to(self.device)
            old_log_probs = torch.FloatTensor(old_log_probs).to(self.device)
            rewards = torch.FloatTensor(rewards).to(self.device)

            weights, biases = self._get_weights()
            logits = functional_mlp(states, weights, biases)
            dist = torch.distributions.Categorical(logits=logits)

            new_log_probs = dist.log_prob(actions)
            ratio = torch.exp(new_log_probs - old_log_probs)

            # Advantage normalization
            adv = (
                (rewards - rewards.mean()) / (rewards.std() + 1e-8)
                if self.normalize_advantage
                else rewards
            )

            surr1 = ratio * adv
            surr2 = torch.clamp(ratio, 1 - self.clip_eps, 1 + self.clip_eps) * adv

            # PPO objective with entropy regularization
            loss = (
                -torch.min(surr1, surr2).mean()
                - self.entropy_coef * dist.entropy().mean()
            )

            self.optimizer.zero_grad()
            loss.backward()
            # Gradient clipping for shared parameters
            torch.nn.utils.clip_grad_norm_(
                list(self.hypernet.parameters())
                + list(self.agent_embeddings.parameters()),
                1,
            )
            self.optimizer.step()
            step_losses.append(loss.item())

        self.loss.append(np.mean(step_losses))
        self.memory.clear()
